version: "3"

# Указываем, какие сервисы DC должен сбилдить и запустить
services:
  # Сервис 'api'
  api:
    # DC берёт DF из папки './api'
    build: ./api
    command: npm run start
    # Если контейнер внепланово остановился или произошла ошибка - DC заново запустит контейнер
    restart: unless-stopped
    ports:
      # Пробрасываем порт контейнера наружу:
      # хост:контейнер
      - "3000:3200"
    # Задаем переменные окружения
    environment:
      # Порт внутри контейнера
      - PORT=3200
